/**
 * Markdown templates for each document section.
 * Templates include Mermaid diagram blocks for sections that benefit from visual diagrams.
 * The `{CONTENT}` placeholder is replaced with the converted markdown content.
 * The `{PROJECT}` placeholder is replaced with the project name.
 * The `{TIMESTAMP}` placeholder is replaced with the current ISO timestamp.
 */

export interface DocTemplate {
  header: string;
  footer: string;
  mermaidHint?: string;  // Mermaid block appended if content doesn't already contain mermaid
}

const SECTION_TEMPLATES: Record<string, DocTemplate> = {
  prd: {
    header: `# Product Requirements Document

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}
> **Status:** Draft

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — PRD*
`,
  },

  roadmap: {
    header: `# Product Roadmap

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Roadmap*
`,
    mermaidHint: `
## Roadmap Timeline

\`\`\`mermaid
gantt
    title Product Roadmap
    dateFormat YYYY-MM-DD
    section Phase 1 - Foundation
        Core Setup           :a1, 2025-01-01, 30d
        MVP Features         :a2, after a1, 45d
    section Phase 2 - Growth
        Advanced Features    :b1, after a2, 60d
        Integrations         :b2, after b1, 30d
    section Phase 3 - Scale
        Performance          :c1, after b2, 30d
        Enterprise Features  :c2, after c1, 45d
\`\`\`

> *Edit the Mermaid diagram above to reflect your actual roadmap milestones.*

`,
  },

  business: {
    header: `# Business Requirements

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Business Requirements*
`,
  },

  data: {
    header: `# Data Dictionary

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Data Dictionary*
`,
    mermaidHint: `
## Entity Relationship Diagram

\`\`\`mermaid
erDiagram
    USER ||--o{ ORDER : places
    USER {
        string id PK
        string name
        string email
    }
    ORDER ||--|{ LINE_ITEM : contains
    ORDER {
        string id PK
        date created_at
        string status
    }
    LINE_ITEM {
        string id PK
        int quantity
        float price
    }
\`\`\`

> *Edit the ER diagram above to reflect your actual data model.*

`,
  },

  app: {
    header: `# Application Architecture

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Application Architecture*
`,
    mermaidHint: `
## Architecture Overview

\`\`\`mermaid
graph TB
    Client[Web / Mobile Client]
    LB[Load Balancer]
    API[API Gateway]
    Auth[Auth Service]
    Core[Core Service]
    DB[(Database)]
    Cache[(Cache)]
    Queue[Message Queue]
    Worker[Background Workers]

    Client --> LB
    LB --> API
    API --> Auth
    API --> Core
    Core --> DB
    Core --> Cache
    Core --> Queue
    Queue --> Worker
    Worker --> DB
\`\`\`

> *Edit the architecture diagram above to reflect your actual system components.*

## Deployment Architecture

\`\`\`mermaid
graph LR
    subgraph Cloud
        subgraph Frontend
            CDN[CDN / Static Host]
        end
        subgraph Backend
            API1[API Server 1]
            API2[API Server 2]
        end
        subgraph Data
            PG[(PostgreSQL)]
            Redis[(Redis)]
        end
    end
    User --> CDN
    CDN --> API1
    CDN --> API2
    API1 --> PG
    API2 --> PG
    API1 --> Redis
    API2 --> Redis
\`\`\`

> *Edit the deployment diagram above to reflect your actual infrastructure.*

`,
  },

  tech: {
    header: `# Technical Specifications

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Technical Specifications*
`,
    mermaidHint: `
## Technology Stack

\`\`\`mermaid
graph TD
    subgraph Frontend
        React[React / Next.js]
        TW[Tailwind CSS]
    end
    subgraph Backend
        Node[Node.js / Express]
        GQL[REST / GraphQL]
    end
    subgraph Infrastructure
        Docker[Docker]
        K8s[Kubernetes]
        CI[CI/CD Pipeline]
    end
    React --> GQL
    GQL --> Node
    Node --> Docker
    Docker --> K8s
    K8s --> CI
\`\`\`

> *Edit the stack diagram above to reflect your actual technology choices.*

`,
  },

  design: {
    header: `# Design System

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Design System*
`,
  },

  adrs: {
    header: `# Architecture Decision Records

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — ADRs*
`,
  },

  specs: {
    header: `# API Specifications

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — API Specifications*
`,
    mermaidHint: `
## API Request Flow

\`\`\`mermaid
sequenceDiagram
    participant C as Client
    participant G as API Gateway
    participant A as Auth Service
    participant S as Core Service
    participant D as Database

    C->>G: HTTP Request
    G->>A: Validate Token
    A-->>G: Token Valid
    G->>S: Forward Request
    S->>D: Query Data
    D-->>S: Result
    S-->>G: Response
    G-->>C: HTTP Response
\`\`\`

> *Edit the sequence diagram above to reflect your actual API flows.*

`,
  },

  'biz-flow': {
    header: `# Business Flows

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Business Flows*
`,
    mermaidHint: `
## Core Business Flow

\`\`\`mermaid
flowchart TD
    Start([User Action]) --> Validate{Valid Input?}
    Validate -->|Yes| Process[Process Request]
    Validate -->|No| Error[Show Error]
    Error --> Start
    Process --> Decision{Approval Required?}
    Decision -->|Yes| Approve[Send for Approval]
    Decision -->|No| Complete[Complete Action]
    Approve --> Review{Approved?}
    Review -->|Yes| Complete
    Review -->|No| Reject[Notify Rejection]
    Complete --> Notify[Send Notification]
    Notify --> End([Done])
\`\`\`

> *Edit the flow diagram above to reflect your actual business processes.*

`,
  },

  'sys-flow': {
    header: `# System Flows

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — System Flows*
`,
    mermaidHint: `
## Authentication Flow

\`\`\`mermaid
sequenceDiagram
    participant U as User
    participant F as Frontend
    participant B as Backend
    participant IdP as Identity Provider
    participant DB as Database

    U->>F: Click Login
    F->>IdP: Redirect to OAuth
    IdP->>U: Show Login Form
    U->>IdP: Enter Credentials
    IdP->>F: Auth Code Callback
    F->>B: Exchange Code for Token
    B->>IdP: Validate Code
    IdP-->>B: Access Token + ID Token
    B->>DB: Create/Update User Session
    B-->>F: JWT Token
    F-->>U: Logged In
\`\`\`

## Data Processing Pipeline

\`\`\`mermaid
flowchart LR
    Input[Input Data] --> Validate[Validate]
    Validate --> Transform[Transform]
    Transform --> Enrich[Enrich]
    Enrich --> Store[(Store)]
    Store --> Index[Index]
    Index --> Cache[Cache]
    Cache --> Serve[Serve API]
\`\`\`

> *Edit the diagrams above to reflect your actual system flows.*

`,
  },

  integrations: {
    header: `# Integrations

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
    footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev) — Integrations*
`,
    mermaidHint: `
## Integration Map

\`\`\`mermaid
graph LR
    App[Your Application]

    App -->|REST API| Ext1[Payment Gateway]
    App -->|Webhook| Ext2[Notification Service]
    App -->|OAuth 2.0| Ext3[Identity Provider]
    App -->|SDK| Ext4[Analytics]
    App -->|SMTP| Ext5[Email Service]

    style App fill:#4F46E5,stroke:#3730A3,color:#fff
    style Ext1 fill:#059669,stroke:#047857,color:#fff
    style Ext2 fill:#D97706,stroke:#B45309,color:#fff
    style Ext3 fill:#DC2626,stroke:#B91C1C,color:#fff
    style Ext4 fill:#7C3AED,stroke:#6D28D9,color:#fff
    style Ext5 fill:#2563EB,stroke:#1D4ED8,color:#fff
\`\`\`

> *Edit the integration map above to reflect your actual third-party services.*

`,
  },
};

/** Default template for unknown section IDs */
const DEFAULT_TEMPLATE: DocTemplate = {
  header: `# {SECTION_NAME}

> **Project:** {PROJECT}
> **Last updated:** {TIMESTAMP}

---

`,
  footer: `
---

*Generated by [Infinia Product Suite](https://infinia.dev)*
`,
};

/**
 * Get the template for a given section ID.
 */
export function getTemplate(sectionId: string): DocTemplate {
  return SECTION_TEMPLATES[sectionId] || DEFAULT_TEMPLATE;
}

/**
 * Apply a template: replace placeholders, insert content, append mermaid if missing.
 */
export function applyTemplate(
  sectionId: string,
  sectionName: string,
  projectName: string,
  markdownContent: string
): string {
  const template = getTemplate(sectionId);
  const timestamp = new Date().toISOString();

  let header = template.header
    .replace(/\{PROJECT\}/g, projectName)
    .replace(/\{TIMESTAMP\}/g, timestamp)
    .replace(/\{SECTION_NAME\}/g, sectionName);

  let output = header + markdownContent;

  // Append mermaid diagrams if the template has them AND the content doesn't already include mermaid
  if (template.mermaidHint && !markdownContent.includes('```mermaid')) {
    output += '\n' + template.mermaidHint;
  }

  output += template.footer;

  return output;
}
